# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b5GDTXI8F_gh46y6JZtruhXxtUozslWN
"""

import pandas as pd # bib propria para trabalhar com dados estruturados
import matplotlib.pyplot as plt
import scipy as sc
import numpy as np # bib propria para trabalhar com numeros
import csv

diferFin = pd.read_csv('dados.txt', delimiter = ' ')

diferFin.head()

"""1) Implemente uma rotina computacional que leia o arquivo de entrada denominado
“dados.txt”, o qual é constituído por duas colunas na seguinte forma (os valores numéricos estão
separados por espaço):

"""

x = diferFin['x']
fx = diferFin['f(x)']

fx1 = np.sin(fx)

h = 1e-2

df = ((x) + (x+h))/h
db = ((x-h) + (x))/h
dc = ((x+h) + (x+h))/(2*h)

dfx = np.cos(fx1) # calculo da derivada de f(x)
Ifx = -(np.cos(fx1)) # calculo da Integral de f(x)
dfx.head()
###print(type(dfx))

difirFinForward = dfx - df # diferença finitas avançada
difirFinForward_1 = difirFinForward[0]
print(difirFinForward_1)

difirFinBackward = dfx - db # diferenças finitas atrasada
difirFinBackward_n = difirFinBackward[9]
print(difirFinBackward_n)

difirFinCen = dfx - dc # diferenças finitas centrada
difirFinCen_n1_n8 = difirFinCen[1:8]
print(difirFinCen_n1_n8)

filds = ('x', 'df(x)')
DerivFin1 = (x, dfx)

filename = 'derivada.txt'
with open (filename, 'w', newline='') as csvfile:
  csvwriter = csv.writer(csvfile, delimiter=' ')
  csvwriter.writerow(filds)
  csvwriter.writerows(DerivFin1)

print(DerivFin1)

"""for k, v in OrdenDerivada.items():
    print(f'{k}={v}')
###OrdenDerivada.head()
OrdenDerivada.sort_values('x', inplace=True)

##########################################################################
##########################################################################

2) Implemente uma rotina computacional que leia o arquivo de entrada denominado
“dados.txt”, o qual é constituído por duas colunas na seguinte forma (os valores numéricos estão
separados por espaço):
"""

difirFinForwardInt = Ifx - df # diferença finitas avançada (integral)
difirFinForwardInt_1 = difirFinForwardInt[0]
print(difirFinForwardInt_1)

difirFinBackwardInt = Ifx - db # diferenças finitas atrasada
difirFinBackwardInt_n = difirFinBackwardInt[9]
print(difirFinBackwardInt_n)

difirFinCenInt = Ifx - dc # diferenças finitas centrada
difirFinCenInt_n1_n8 = difirFinCenInt[1:8]
print(difirFinCenInt_n1_n8)

filds = ('x', 'df(x)')
IntFin1 = (x, Ifx)

filename = 'integral.txt'
with open (filename, 'w', newline='') as csvfile:
  csvwriter = csv.writer(csvfile, delimiter=' ', quotechar='|')
  csvwriter.writerow(filds)
  csvwriter.writerows(IntFin1)

print(IntFin1)

